# Generated by Django 4.2.24 on 2025-10-17 03:26

import cases.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(blank=True, max_length=32, unique=True)),
                ('phone', models.CharField(max_length=13, validators=[cases.models.validate_phone_12])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_type', models.CharField(choices=[('Auto Accident', 'Auto Accident'), ('Work Injury', 'Work Injury'), ('Slip and Fall', 'Slip and Fall'), ('Medical Negligence', 'Medical Negligence'), ('Product Liability', 'Product Liability')], max_length=32)),
                ('case_status', models.CharField(choices=[('Case Approved', 'Case Approved'), ('Case Signed', 'Case Signed'), ('Court Date Scheduled', 'Court Date Scheduled'), ('Documents Received', 'Documents Received'), ('Hearing Scheduled', 'Hearing Scheduled'), ('Insurance Contacted', 'Insurance Contacted'), ('Mediation Scheduled', 'Mediation Scheduled'), ('Pending Insurance Response', 'Pending Insurance Response'), ('Settlement Approved', 'Settlement Approved'), ('Treatment Scheduled', 'Treatment Scheduled')], max_length=32)),
                ('date_opened', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.client')),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.firm')),
            ],
            options={
                'ordering': ['-last_update'],
                'indexes': [models.Index(fields=['case_type'], name='cases_case_case_ty_2efb82_idx'), models.Index(fields=['case_status'], name='cases_case_case_st_46849d_idx'), models.Index(fields=['date_opened'], name='cases_case_date_op_d81986_idx'), models.Index(fields=['last_update'], name='cases_case_last_up_e451fa_idx')],
            },
        ),
    ]
