# Generated by Django 4.2.24 on 2025-10-20 12:46

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='client_phone',
            field=models.CharField(max_length=10, validators=[cases.models.validate_phone_10]),
        ),
    ]
