# Generated by Django 4.2.24 on 2025-10-26 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_alter_case_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='attorney',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
