# Generated by Django 4.2.24 on 2025-11-05 09:52

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_attorney'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='firm_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='case',
            name='firm_phone',
            field=models.CharField(blank=True, max_length=10, validators=[cases.models.validate_phone_10]),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['firm_email'], name='cases_case_firm_em_6f7861_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['firm_phone'], name='cases_case_firm_ph_ca46be_idx'),
        ),
    ]
