# Generated by Django 4.2.24 on 2025-10-20 13:38

import authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attorney',
            fields=[
            ],
            options={
                'verbose_name': 'Attorney',
                'verbose_name_plural': 'Attorneys',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.customuser',),
            managers=[
                ('objects', authentication.models.CustomUserManager()),
            ],
        ),
    ]
