# Generated by Django 4.2.24 on 2025-11-06 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(db_index=True, max_length=32)),
                ('device_id', models.CharField(max_length=512)),
            ],
            options={
                'indexes': [models.Index(fields=['client_code'], name='notificatio_client__5b8d46_idx'), models.Index(fields=['device_id'], name='notificatio_device__2aa6c3_idx')],
                'unique_together': {('client_code', 'device_id')},
            },
        ),
        migrations.CreateModel(
            name='AttorneyDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attorney_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_cec95f_idx'), models.Index(fields=['device_id'], name='notificatio_device__35c4d7_idx')],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
