# Generated by Django 4.2.24 on 2025-11-06 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attorneydevice',
            name='notificatio_device__35c4d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientdevice',
            name='notificatio_device__2aa6c3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='attorneydevice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='clientdevice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attorneydevice',
            name='device_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clientdevice',
            name='device_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='attorneydevice',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attorney_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientdevice',
            name='client_code',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.RemoveField(
            model_name='attorneydevice',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='clientdevice',
            name='device_id',
        ),
    ]
